### ISSUE TITLE
Unale to sign up.

### ISSUE THREAD

**Issue by mzch** [Myles-Trevino/Hyperpass#1]
I tried to sign up to https://hyperpass.org, but my browser reported an error and failed.

<img width="1501" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/134016343-8394a2cc-067a-484e-b63f-23a4225e6384.png">

Could you fix this?

OS: macOS 11.6 (Big Sur)
Browser: Chrome 93.0.4577.82

p.s.
I'd like to self host this app, but it seems to have fixed api url. Could you please update desktop, mobile app and browser extension for users to set self hosted url like BItwarden?

**Comment by mzch** [comment]
Fixed? Now I can sign up and login. Thanks. But there is another error.
I tried to import data from Bitwarden, but Invalid files error occurred:

![ScreenShot](https://user-images.githubusercontent.com/621178/134070142-789a63d6-9ac4-4448-a75e-85257c779614.png)

Please look into this error.

**Comment by Myles-Trevino** [comment]
Thank you for testing. Regarding the signup error, a MongoDB update silently changed how it needed to be imported, but it should be fixed now. I've also started making some changes towards making self-hosting easier. Please check out the new [article on self-hosting](https://hyperpass.org/support/faq/how-do-i-self-host-hyperpass). It will take some more time for those changes to be available on all platforms (plugin/app store screening) and you may need to clear cache for it to update on browser. For the import error, please try again using a CSV export.

**Comment by mzch** [comment]
Great! I can import my vault now. Thanks, @Myles-Trevino !
And I wll try to self host by myself. Thanks again. :)
