### ISSUE TITLE
[HELP] CORS?

### ISSUE THREAD

**Issue by mzch** [Myles-Trevino/Hyperpass#2]
I run Hyperpass instance on `passdepository.com` and API serever is `api.passdepository.com`
But I encountered the following message.

```
Access to XMLHttpRequest at 'https://api.passdepository.com/get-minimum-version' from origin 'https://passdepository.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Could you please tell me how to fix this?

**Comment by mzch** [comment]
Of couse, when I set `api.hyperpass.org` to API Server, everything is OK.

**Comment by mzch** [comment]
- My `.env` as below:
```
NODE_ENV=production
MONGODB_URI=mongodb://hyperpass:password@192.168.207.10:27017/hyperpass
PORT=3000
EMAIL_ADDRESS=no-reply@passdepository.com
EMAIL_HOST=mymailserver
EMAIL_PORT=587
EMAIL_USERNAME=admin@example.com
EMAIL_PASSWORD='password'
```
- API sever log : `node /usr/bin/node ./builds/hyperpass-api/main.js`
```
9月 21 03:31:44 n14 node[90273]: Starting Express on port 3000.
```

- Website server log : `node ./builds/hyperpass-website/server/main.js`
```
 9月 21 03:33:45 n14 node[90341]: The Hyperpass website server has been started on port 4001 (http://localhost:4001). 9月 21 03:33:45 n14 node[90341]: The Hyperpass website server has been started on port 4001 (http://localhost:4001).
```

**Comment by mzch** [comment]
From desktop app I can sign up and login successully. But browser extension reports the same error.

**Comment by Myles-Trevino** [comment]
To fix this you need to add CORS headers to the API responses. I've just added an option to make Express do this by setting the `ENABLE_CORS=true` environment variable, which may solve your problem. I'll test this more thoroughly later. However, if you are serving through a publicly accessible domain name, it may be better to use a webserver like NGINX or Apache as a reverse proxy and configure headers there. That way you can also configure things like rate limiting and caching so that you don't get undesired requests.

**Comment by mzch** [comment]
Thanks for your quick fix. I rebuit Hyperpass. Adding `ENABLE_CORS=true` to `.env`, I re-ran and tried to login Hyperpass, but:

![ScreenShot](https://user-images.githubusercontent.com/621178/134207653-e74bb8e8-437a-4b51-8b9a-dacfc8bf1eff.png)

What's wrong with me?

**Comment by mzch** [comment]
p.s.
When clicking Log in, Hyperpass shows `Could not complete the request.` error dialog.

**Comment by Myles-Trevino** [comment]
I've just gotten around to testing the Express CORS option and noticed it was not being enabled properly. Now that it's fixed, I have gotten a self-hosted setup using just Express working on my end. It should now work with your setup as well.

**Comment by mzch** [comment]
Awesome! all issues are fixed! Thanks, @Myles-Trevino !
I set headers in Apache config, but somehow they aren't effective.
```
	<Location />
		Header set Access-Control-Allow-Origin "*"
		Header set Access-Control-Allow-Headers "Content-Type, Origin, Accept"
		Header set Access-Control-Allow-Methods "GET, PUT, OPTIONS"
		ProxyPass http://127.0.0.1:3000/ nocanon
		ProxyPassReverse http://127.0.0.1:3000/
	</Location>
```

**Comment by mzch** [comment]
p.s.
Desktop app can't be download from `https://hyperpass.org/downloads`, the site returns 404 error.

p.s.2
I hope that `autofill` function will be added to browsers extensions...

**Comment by Myles-Trevino** [comment]
Download links are fixed now. For autofill with keyboard shortcuts, please see [this article](https://hyperpass.org/support/common-tasks/autofilling-usernames-and-passwords). For autofill without needing to press anything, that involves more security risks and complexity for what I see as only a minor improvement in ease of use over keybinds, so I have avoided adding that.

**Comment by mzch** [comment]
Thanks for your reply. I missed context menu. :-P
